

services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata_postgres17:/var/lib/postgresql/data
    networks:
      - postgres_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2023-10-07T15-07-38Z
    restart: unless-stopped
    ports:
      - "9000:9000"   # API S3
      - "9001:9001"   # Console Web
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - postgres_net

  app:
    build: .
    container_name: seletivo-api
    restart: unless-stopped
    depends_on:
      - postgres
      - minio
    ports:
      - "8080:8080"
    environment:
          SPRING_PROFILES_ACTIVE: docker
    env_file:
      - .env
    networks:
      - postgres_net

volumes:
  pgdata_postgres17:
  minio_data:

networks:
  postgres_net:
    driver: bridge
