spring.application.name=seletivo

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true

# Seguranca
security.jwt.enabled=true

# Health/Liveness/Readiness
management.endpoints.web.exposure.include=health
management.health.probes.enabled=true

# API Externa

