#Configuracoes para rodar local
#SPRING_PROFILES_ACTIVE=local

# Postgres local
spring.datasource.url=jdbc:postgresql://localhost:5432/bancoseletivo
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# MinIO local
minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin123
minio.bucket=bancoseletivo-arquivos
minio.presigned.expiry-minutes=30