spring.application.name=seletivo

# Postgres
spring.datasource.url=jdbc:postgresql://localhost:5433/bancoseletivo
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# MinIO
minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin123
minio.bucket=bancoseletivo-arquivos
minio.presigned.expiry-minutes=30

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true

# Seguranca
#security.jwt.enabled=true
security.jwt.enabled=false