#Configuracoes para rodar via Docker
#environment:
#  SPRING_PROFILES_ACTIVE: docker

# Postgres (container Docker)
spring.datasource.url=jdbc:postgresql://postgres:5432/bancoseletivo
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# MinIO (container Docker)
minio.url=http://minio:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin123
minio.bucket=bancoseletivo-arquivos
minio.presigned.expiry-minutes=30
#minio.internal-url=http://minio:9000
#minio.public-url=http://localhost:9000